### ISSUE TITLE
Move to github.com/canonical

### ISSUE THREAD

**Issue by doismellburning** [canonical/serial-vault#293]

**Comment by glower** [comment]
One idea is: we can migrate the project to use `gopkg.in` internally, like it's done in `https://github.com/go-yaml/yaml` or `https://github.com/go-check/check`
We will use something like `gopkg.in/canonical/serial-vault` or `gopkg.in/serial-vault.v1` internally in the project (we need to do this first). Then we can move the project to `github.com/canonical` and change the configuration in `gopkg.in`.

**Comment by doismellburning** [comment]
https://docs.github.com/en/github/administering-a-repository/transferring-a-repository FYI

**Comment by alex-ramanau** [comment]
The repo was migrated to https://github.com/canonical/serial-vault together with other repos a couple of months ago.
The redirect rule was configured to keep CI working.

**Comment by doismellburning** [comment]
Nicely done :)

**Comment by glower** [comment]
👍
